### PR TITLE
fix(http client): set reuseaddr and nodelay.

### PR DESCRIPTION
**Pull request by niklasad1**

### CODE REVIEW

**Review by dvdplm — APPROVED** [review]

**Comment by dvdplm** [comment]
@niklasad1 Do we still want to do this, even though it doesn't fix the benches on macos? I didn't look into the windows CI failure, maybe we need some `cfg`-fu to make it work?

**Comment by niklasad1** [comment]
> @niklasad1 Do we still want to do this, even though it doesn't fix the benches on macos? I didn't look into the windows CI failure, maybe we need some cfg-fu to make it work?

Good catch I forgot about this one.
Yes, I think we should include this anyway.

**Review by lexnv — APPROVED** [review]

**Review by jsdw — APPROVED** [review]
Looks sane to me; I'm not really sure of the ramifications of reuseport and reuseaddress being set though!

**Comment by niklasad1** [comment]
> Looks sane to me; I'm not really sure of the ramifications of reuseport and reuseaddress being set though!

Yeah, I'm not sure about reuseport at least I'll remove it.

**Review by TarikGul — APPROVED** [review]

**Pull request merged**
