### PR TITLE
Derive `Clone` for `WsClient`

### PR DESCRIPTION
**Pull request by HCastano**
In the [`parity-bridges-common`](https://github.com/paritytech/parity-bridges-common) we currently rely on `WsClient` being `Clone`. This was removed 
in `jsonrpsee-ws-client` `v0.2.0-alpha.3`, which makes upgrading from `alpha.2` a breaking
change for us.

This PR makes `WsClient` `Clone`-able again.

### CODE REVIEW

**Review by niklasad1 — COMMENTED** [review]
Hey Hernando,

We don't respect semver in the alpha releases,

> A pre-release version indicates that the version is unstable and might not satisfy the intended compatibility requirements as denoted by its associated normal version`

The client is not `Clone` anymore see https://github.com/paritytech/jsonrpsee/pull/243#discussion_r594153898. Please convince me why it should be `Clone`

Can't you pin it to `=alpha.2` in your `Cargo.toml`?

**Comment by HCastano** [comment]
> Hey Hernando,
> 
> > which makes upgrading from alpha.2 a breaking
> > change for us.
> 
> [pre-releases may have breaking changes according to semver](https://semver.org/#spec-item-9) however it's not a great user-experience I guess but I thought `x.x.x-alpha` was sufficient to indicate that it may contain breaking changes.

That's a fair point. I guess I'm just used to expecting stability between releases in general.

> The client is not `Clone` anymore see [#243 (comment)](https://github.com/paritytech/jsonrpsee/pull/243#discussion_r594153898). Please convince me why it should be `Clone`

I don't have a good answer other than keeping the status quo. I'll give a go to `Arc`-ifying stuff on our end and close this PR if that works.

> Can't you pin it to `=alpha.2` in your `Cargo.toml`?

No. This is because we want to be integrated with the Polkadot repo, which is already using `alpha.3` (which comes from Substrate).

**Comment by niklasad1** [comment]
> No. This is because we want to be integrated with the Polkadot repo, which is already using alpha.3 (which comes from Substrate).

Ok, I see watch out for https://github.com/paritytech/jsonrpsee/issues/254 then because `substrate` uses the feature `tokio02` on the http client.

**Comment by HCastano** [comment]
Closing in favour of https://github.com/paritytech/parity-bridges-common/pull/892.

**Pull request closed without merging**
