### PR TITLE
Fix clippy warnings

### PR DESCRIPTION
**Pull request by lexnv**
Fix clippy warnings.

Use `actions-rs/clippy-check@v1` which posts all lints as annotations for the pushed commit.

### Clippy Check

github_lint

### CODE REVIEW

**Review by niklasad1 — COMMENTED** [review]
The changes looks good but I'm still against failing the CI just because some opinionated style was denied by clippy.

It's enough for the GHA to show to errors/warnings but it seems to be gone these days

**Comment by TarikGul** [comment]
Is there a specific PR these warnings are coming from that I can check out?

**Comment by niklasad1** [comment]
> Is there a specific PR these warnings are coming from that I can check out?

https://gitlab.parity.io/parity/mirrors/jsonrpsee/-/jobs/1732205

So before the GitHub UI show this warnings inline in the files when reviewing the code, not sure why it doesn't show up anymore

**Review by niklasad1 — APPROVED** [review]
:ok_hand:

**Review by TarikGul — APPROVED** [review]
Nice job, LGTM!

**Pull request merged**
