### PR TITLE
chore(deps): tokio ^1.16

### PR DESCRIPTION
**Pull request by niklasad1**

### CODE REVIEW

**Comment by Xanewok** [comment]
Is this fix for a specific bug/unsoundness/perf issue?

**Comment by niklasad1** [comment]
> Is this fix for a specific bug/unsoundness/perf issue?

Unsoundness https://rustsec.org/advisories/RUSTSEC-2021-0124.html, we are not using `tokio::sync::oneshot` anyway but I want to get rid of https://deps.rs/crate/jsonrpsee-client-transport/0.15.1

**Review by Xanewok — APPROVED** [review]
Okay, sounds good!

**Review by lexnv — APPROVED** [review]
Nice! 👍

**Pull request merged**
