### PR TITLE
chore(scripts): publish script

### PR DESCRIPTION
**Pull request by niklasad1**

### CODE REVIEW

**Comment by dvdplm** [comment]
@tomusdrw 's [script](https://github.com/paritytech/jsonrpc/blob/master/_automate/publish.sh) seems to do a bit more than this and has been working well over there, just saying. :)

**Comment by niklasad1** [comment]
yeah, it's inspired by that ofcourse but I want to actually check all crates could be published before creating the tag

but we could use `https://github.com/paritytech/cargo-unleash` perhaps instead.

**Comment by dvdplm** [comment]
> but we could use `https://github.com/paritytech/cargo-unleash` perhaps instead.

oh, I like that idea.

**Comment by tomusdrw** [comment]
>  but I want to actually check all crates could be published before creating the tag

You can still do that with my script just passing `--dry-run` to parameters (note `$@` near `cargo publish`).

However it only works if the published crates can use older (already published) versions. I.e. it won't work if you do a major release and have dependent crates for instance.

**Comment by niklasad1** [comment]
> You can still do that with my script just passing --dry-run to parameters (note $@ near cargo publish).

Right, my bash reading skillz are poor nowdays.

> However it only works if the published crates can use older (already published) versions. I.e. it won't work if you do a major release and have dependent crates for instance.

yeah good point

**Review by dvdplm — APPROVED** [review]

**Pull request merged**
